---
title: "Publications"
---

## En relecture ou soumise

1. **Past trajectory of a Northwest Europe socio-ecosystem at the land-sea interface: Case study of the northern watersheds of the Bay of Brest over the last 150 years**\
    Valero, C., Penaud, A., Vidal, M., Goubert, E., Dessandier, P.-A., Schmidt, S., Glémarec, E., **Brigode, P.**, Bosseboeuf, L., Paulet, Y.-M., Sutton, J., Ailliot, P., Derrien, J.-M., Niass, N. C., Liorzou, C., Saguet, L., Guérin, T., & Lambert, C.\
    En relecture dans *Palaeogeography, Palaeoclimatology, Palaeoecology*.\
    Preprint: <https://doi.org/10.2139/ssrn.5494589>

1.  **On the impact of anomalous streamflow values on hydrological model parameter values, performance and indicator values**\
    Strohmenger, L., **Brigode, P.**, & Thirel, G.\
    Soumis à *Hydrological Sciences Journal*.

------------------------------------------------------------------------

## Articles publiés dans des revues à comité de lecture

1. **Using century-long reanalysis and a rainfall-runoff model to explore multi-decadal variability in catchment hydrology at the European scale**\
    **Brigode, P.**, Oudin, L.\
    *Hydrology and Earth System Sciences* (2025)\
    <https://doi.org/10.5194/hess-29-5535-2025>

1. **Wet snow avalanches on Corsica Island: a long-term perspective from lake sediments**\
    Sabatier, P., **Brigode, P.**, Bisquert, A., Eckert, N., Giacona, F., Deschâtres, M., Bauve, V., Kelner, M., Debret, M., Bellingery, M.-C., Copard, Y., Malet, E., Didier, J., Huneau, F., Garel, E., Vannière, B.\
    *Sedimentologika* (2025)\
    <https://doi.org/10.57035/journals/sdk.2025.e31.1669>

1. **Improved predictions in ungauged basins using flood marks**\
    Oudin, L., Caupin, R., **Brigode, P.**\
    *Journal of Hydrology* (2025)\
    <https://doi.org/10.1016/j.jhydrol.2025.133145>

1. **CAMELS-FR dataset: a large-sample hydroclimatic dataset for France to explore hydrological diversity and support model benchmarking**\
    Delaigue, O., Mendoza Guimarães, G., **Brigode, P.**, Génot, B., Perrin, C., Soubeyroux, J.-M., Janet, B., Addor, N., Andréassian, V.\
    *Earth System Science Data* (2025)\
    <https://doi.org/10.5194/essd-17-1461-2025>

1. **Spatio-temporal characteristics of heavy precipitation events observed over the last decade on the Eastern French Mediterranean coastal area**\
    Vigoureux, S., **Brigode, P.**, Ramos, M.-H., Poggio, J., Dreyfus, R., Moreau, E., Laroche, C., Tric, E.\
    *Journal of Hydrology: Regional Studies* (2024)\
    <https://doi.org/10.1016/j.ejrh.2024.101988>

1. **The IAHS Science for Solutions decade, with Hydrology Engaging Local People IN a Global world (HELPING)**\
    Arheimer, B., et al.\
    *Hydrological Sciences Journal* (2024)\
    <https://doi.org/10.1080/02626667.2024.2355202>

1. **50-Year Seasonal Variability in East African Droughts and Floods Recorded in Central Afar Lake Sediments (Ethiopia) and Their Connections with the El Niño–Southern Oscillation**\
    Mologni, C., Revel, M., Chaumillon, E., Malet, E., Coulombier, T., Sabatier, P., **Brigode, P.**, Gwenael, H., Develle, A.-L., Schenini, L., Messous, M., Davtian, G., Carré, A., Bosch, D., Volto, N., Ménard, C., Khalidi, L., Arnaud, F.\
    *Climate of the Past* (2024)\
    <https://doi.org/10.5194/cp-20-1837-2024>

1. **Consensus hydrologique de la tempête Alex du 2 et 3 octobre 2020 dans les Alpes-Maritimes**\
    Pons, F., Bonnifait, L., Criado, D., Payrastre, O., Billaud, F., **Brigode, P.**, Fouchier, C., Gourbesville, P., Kuss, D., Le Nouveau, N., Martin, O., Martins, C., Nomis, S., Paquet, E., Cardelli, B.\
    *La Houille Blanche* (2024)\
    <https://doi.org/10.1080/27678490.2024.2363619>

1. **Simbi: Historical Hydro-Meteorological Time Series and Signatures for 24 Catchments in Haiti**\
    Bathelemy, R., **Brigode, P.**, Andréassian, V., Perrin, C., Moron, V., Gaucherel, C., Tric, E., Boisson, D.\
    *Earth System Science Data* (2024)\
    <https://doi.org/10.5194/essd-16-2073-2024>

1. **On the visual detection of non-natural records in streamflow time series: challenges and impacts**\
    Strohmenger, L., Sauquet, E., Bernard, C., Bonneau, J., Branger, F., Bresson, A., **Brigode, P.**, Buzier, R., Delaigue, O., Devers, A., Evin, G., Fournier, M., Hsu, S.-C., Lanini, S., de Lavenne, A., Lemaitre-Basset, T., Magand, C., Mendoza Guimarães, G., Mentha, M., Munier, S., Perrin, C., Podechard, T., Rouchy, L., Sadki, M., Soutif-Bellenger, M., Tilmant, F., Tramblay, Y., Véron, A.-L., Vidal, J.-P., Thirel, G.\
    *Hydrology and Earth System Sciences* (2023)\
    <https://doi.org/10.5194/hess-27-3375-2023>

1. **airGRteaching: an open-source tool for teaching hydrological modeling with R**\
    Delaigue, O., **Brigode, P.**, Thirel, T., Coron, L.\
    *Hydrology and Earth System Sciences* (2023)\
    <https://doi.org/10.5194/hess-27-3293-2023>

1. **How can we benefit from regime information to make more effective use of long short-term memory (LSTM) runoff models?**\
    Hashemi, R., **Brigode, P.**, Garambois, P.-A., Javelle, P.\
    *Hydrology and Earth System Sciences* (2022)\
    <https://doi.org/10.5194/hess-26-5793-2022>

1. **Rainfall in the Greater and Lesser Antilles: performance of four gridded datasets on a daily timescale**\
    Bathelemy, R., **Brigode, P.**, Boisson, D., Tric, E.\
    *Journal of Hydrology: Regional Studies* (2022)\
    <https://doi.org/10.1016/j.ejrh.2022.101203>

1. **Crue du 23 novembre 2019 sur la Côte d’Azur : comparaison de débits estimés par LSPIV et par modélisation hydrologique**\
    Vigoureux, S., Liebard, L.-L., Chonoski, A., Robert, E., Torchet, L., Poveda, V., Leclerc, F., Billant, J., Rousseau, G., Delestre, O., **Brigode, P.**\
    *La Houille Blanche* (2022)\
    <https://doi.org/10.1080/27678490.2022.2101391>

1. **Tempête Alex du 2 octobre 2020 dans les Alpes-Maritimes : une contribution de la communauté scientifique à l’estimation des débits de pointe des crues**\
    Payrastre, O., Bonnifait, L., **Brigode, P.**, Astagneau, P., Baise, A., Belleville, A., Bouamara, N., Bourgin, F., Breil, P., Brunet, P., Cerbelaud, A., Courapied, F., Devreux, L., Dreyfus, R., Gaume, E., Nicolle, P., Nomis, S., Poggio, J., Pons, F., Rabab, Y., Sevrez, D.\
    *La Houille Blanche* (2022)\
    <https://doi.org/10.1080/27678490.2022.2082891>

1. **Brief communication: Seismological analysis of flood dynamics and hydrologically-triggered earthquake swarms during storm Alex**\
    Chmiel, M., Godano, M., Piantini, M., **Brigode, P.**, Gimbert, F., Bakker, M., Courboulex, F., Ampuero, J.-P., Rivet, D., Sladen, A., Ambrois, D., Chapuis, M.\
    *Natural Hazards and Earth System Sciences* (2022)\
    <https://doi.org/10.5194/nhess-22-1541-2022>

1. **Inondations sur la Côte d’Azur : bilan hydro-météorologique des épisodes de 2015 et 2019**\
    **Brigode, P.**, Vigoureux, S., Delestre, O., Nicolle, P., Payrastre, O., Dreyfus, R., Nomis, S., Salvan, L.\
    *La Houille Blanche* (2021)\
    <https://doi.org/10.1080/27678490.2021.1976600>

1. **Reconstructing past hydrology of eastern Canadian boreal catchments using clastic varved sediments and hydroclimatic modeling: 160 years of fluvial inflows**\
    Gagnon-Poiré, A., **Brigode, P.**, Francus, P., Fortin, D., Lajeunesse, P., Trottier, A.-P., Dorion, H.\
    *Climate of the Past* (2021)\
    <https://doi.org/10.5194/cp-17-653-2021>

1. **Tree-Ring Stable Isotopes for Regional Discharge Reconstruction in Eastern Labrador and Teleconnection with the Arctic Oscillation**\
    Dinis, L., Bégin, C., Savard, M., Marion, J., **Brigode, P.**, Alvarez, C.\
    *Climate Dynamics* (2019)\
    <https://doi.org/10.1007/s00382-019-04731-2>

1. **Une cartographie de l’écoulement des rivières de Corse**\
    **Brigode, P.**, Lilas, D., Andréassian, V., Nicolle, P., Le Moine, N., Perrin, C., Gremminger, S., Augeard, B.\
    *La Houille Blanche* (2019)\
    <https://doi.org/10.1051/lhb/2019009>

1. **Changes in French weather pattern seasonal frequencies projected by a CMIP5 ensemble**\
    **Brigode, P.**, Gérardin, M., Bernardara, P., Gailhard, J., Paquet, E., Ribstein, P.\
    *International Journal of Climatology* (2018)\
    <https://doi.org/10.1002/joc.5549>

1. **Streamflow variability over the 1881–2011 period in northern Québec: comparison of hydrological reconstructions based on tree rings and geopotential height field reanalysis**\
    **Brigode, P.**, Brissette, F., Nicault, A., Perreault, L., Kuentz, A., Mathevet, T., Gailhard, J.\
    *Climate of the Past* (2016)\
    <https://doi.org/10.5194/cp-12-1785-2016>

1. **Dependence of model-based extreme flood estimation to the calibration period: the case study of the Kamp River (Austria)**\
    **Brigode, P.**, Paquet, E., Bernardara, P., Gailhard, J., Garavaglia, F., Ribstein, P., Bourgin, F., Perrin, C., Andréassian, V.\
    *Hydrological Sciences Journal* (2015)\
    <https://doi.org/10.1080/02626667.2015.1006632>

1. **Parameter transferability under changing climate: case study with a land surface model in the Durance watershed, France**\
    Magand, C., Ducharne, A., Le Moine, N., **Brigode, P.**\
    *Hydrological Sciences Journal* (2015)\
    <https://doi.org/10.1080/02626667.2014.993643>

1. **Méthodes probabilistes et déterministes d’estimation des débits extrêmes: Comparaison de résultats sur deux bassins versants de Colombie Britannique (Canada)**\
    **Brigode, P.**, Mićović, Z., Bernardara, P., Paquet, E., Gailhard, J., Garavaglia, F., Garçon, R., Ribstein, P.\
    *La Houille Blanche* (2014)\
    <https://doi.org/10.1051/lhb/20150036>

1. **Sensitivity analysis of SCHADEX extreme flood estimates to observed hydro-meteorological variability**\
    **Brigode, P.**, Bernardara, P., Paquet, E., Gailhard, J., Garavaglia, F., Merz, R., Mićović, Z., Lawrence, D., Ribstein, P.\
    *Water Resources Research* (2014)\
    <https://doi.org/10.1002/2013WR013687>

1. **Linking ENSO and heavy rainfall events over Coastal British Columbia through a weather pattern classification**\
    **Brigode, P.**, Mićović, Z., Bernardara, P., Paquet, E., Garavaglia, F., Gailhard, J., Ribstein, P.\
    *Hydrology and Earth System Sciences* (2013)\
    <https://doi.org/10.5194/hess-17-1455-2013>

1. **Optimization of the geopotential heights information used in a rainfall based weather patterns classification over Austria**\
    **Brigode, P.**, Bernardara, P., Gailhard, J., Garavaglia, F., Ribstein, P., Merz, R.\
    *International Journal of Climatology* (2013)\
    <https://doi.org/10.1002/joc.3535>

1. **Hydrological model parameters instability: a source of additional uncertainty in estimating the hydrological impacts of climate change?**\
    **Brigode, P.**, Oudin, L., Perrin, C.\
    *Journal of Hydrology* (2013)\
    <https://doi.org/10.1016/j.jhydrol.2012.11.012>


------------------------------------------------------------------------

## Articles dans des actes de colloques avec comité de lecture

1. **Are hydrologic-hydraulic coupling approaches able to reproduce Alex flash-flood dynamics and impacts on southeastern French headwaters?**\
   **Brigode, P.**, Bourgin, F., Yassine, R., Delestre, O., Lagrée, P.-Y.\
   In *Advances in Hydroinformatics*, Springer Water (2022)\
   <https://doi.org/10.1007/978-981-19-1600-7_27>

1. **Simulation of the Alex Storm Flash-Flood in the Vésubie Catchment (South Eastern France) Using Telemac-2D Hydraulic Code.**\
   Yassine, R., Lastes, M., Argence, A., Gandouin, A., Imperatrice, C., Michel, P., Zhang, R., **Brigode, P.**, Delestre, O., Taccone, F.\
   In *Advances in Hydroinformatics*, Springer Water (2022)\
   <https://doi.org/10.1007/978-981-19-1600-7_52>

1. **Modelling Culverts in Basilisk.**\
   Amama, Z., Branco, N., Mangara, C., Mbonyinshuti, K., Yu, Q., Cottancin, T., Vigoureux, S., **Brigode, P.**, Delestre, O., Lagrée, P.-Y.\
   In *Advances in Hydroinformatics*, Springer Water (2022)\
   <https://doi.org/10.1007/978-981-19-1600-7_8>

1. **Comparison of Streamflow Estimated by Image Analysis (LSPIV) and by Hydrologic and Hydraulic Modelling on the French Riviera During November 2019 Flood.**\
   Vigoureux, S., Liebard, L.-L., Chonoski, A., Robert, E., Torchet, L., Poveda, V., Leclerc, F., Billant, J., Dumasdelage, R., Rousseau, G., Delestre, O., **Brigode, P.**\
   In *Advances in Hydroinformatics*, Springer Water (2022)\
   <https://doi.org/10.1007/978-981-19-1600-7_16>

1. **Real-Time Inundation Mapping with a 2D Hydraulic Modelling Tool Based on Adaptive Grid Refinement: The Case of the October 2015 French Riviera Flood.**\
   Kirstetter, G., Bourgin, F., **Brigode, P.**, Delestre, O.\
   In *Advances in Hydroinformatics*, Springer Water (2020)\
   <https://doi.org/10.1007/978-981-15-5436-0_25>

1. **airGR and airGRteaching: Two Open-Source Tools for Rainfall-Runoff Modeling and Teaching Hydrology.**\
   Delaigue, O., Thirel, G., Coron, L., **Brigode, P.**\
   *13th International Conference on Hydroinformatics (HIC 2018)*, EPiC Series in Engineering (2018)\
   <https://doi.org/10.29007/qsqj>
   

------------------------------------------------------------------------

## Articles sans comité de lecture

1. **Les cours d’eau sous leur meilleur ProfHyl**\
   Delaigue, O., Andréassian, V., Génot, B., **Brigode, P.**, Magand, C.\
   *Sciences Eaux & Territoires*, n°42 (2023)\
   <https://doi.org/10.20870/Revue-SET.2023.42.7291>

1. **L’exemple venu d’outre-Manche**\
   Bressan, Y., **Brigode, P.**\
   *Le Courrier de la Nature*, n°342 (2024)\
   <https://www.snpn.com/produit/le-courrier-de-la-nature-n-342-septembre-2024/>

------------------------------------------------------------------------

## Chapitre de livres

1. **Reconstitution historique des séries hydrologiques**\
   **Brigode, P.**, et al.\
   In *Les ressources en eau et le changement climatique en Provence-Alpes-Côte d’Azur*, Cahiers du GREC-PACA (2017)\
   ISBN: 978-2956-0-0605-3

------------------------------------------------------------------------

## Thèse et rapport de Master

1. **Changement climatique et risque hydrologique : évaluation de la méthode SCHADEX en contexte non-stationnaire.**\
   **Brigode, P.**\
   Thèse de doctorat, UPMC (2013)\
   <https://tel.archives-ouvertes.fr/tel-00851384/>

1. **Modélisation hydrologique en contexte de changement climatique : incertitudes liées aux paramètres de modèles conceptuels pluie-débit.**\
   **Brigode, P.**\
   Mémoire de Master 2, UPMC (2010)\
   <http://m2hh.metis.upmc.fr/wp-content/uploads/arch/memoires2010/Brigode-rapportHH0910.pdf>

------------------------------------------------------------------------

## Rapports techniques

3. **Lutte contre les inondations sur le bassin versant de la Zorn : comparaison de méthodes de prédétermination des débits caractéristiques de crues.**\
   Nicolle, P., **Brigode, P.**, Perrin, C.\
   Irstea - UR HBAN – Antony (2015)

2. **Reconstitution de 55 années de débits sur plus de 10 000 points non-jaugés en France par régionalisation d’un modèle pluie-débit.**\
   **Brigode, P.**, Andréassian, V., Bourgin, F., Lobligeois, F.\
   Partenariat ONEMA-Irstea – Hydrologie des étiages (2014)

1. **Cartographie du débit de référence d’étiage et du débit moyen en Corse : une approche distribuée pour garantir la continuité des estimations le long du réseau hydrographique.**\
   **Brigode, P.**, Andréassian, V., Nicolle, P., Le Moine, N., Perrin, C.\
   Partenariat ONEMA-Irstea – Hydro-morphologie (2014)